package com.example.EcomerceUribe.ayudas;

public enum Departamentos {

    AMAZONAS, ANTIOQUIA, ARAUCA, ATLANTICO, BOLIVAR, BOYACA, CALDAS, CAQUETA, CASANARE, CAUCA,
    CESAR, CHOCO, CORDOBA, CUNDINAMARCA, GUAINIA, GUAVIARE, HUILA, LA_GUAJIRA, MAGDALENA,
    META, NARINO, NORTE_DE_SANTANDER, PUTUMAYO, QUINDIO, RISARALDA, SAN_ANDRES, SANTANDER,
    SUCRE, TOLIMA, VALLE_DEL_CAUCA, VAUPES, VICHADA

}
